**** PROPERTIES SKAFFOLDER ****
{
    "forEachObj": "oneTime",
    "_partials": []
}
**** END PROPERTIES SKAFFOLDER ****
# Create image based on the official Skaffolder JAVA Oracle image from dockerhub
FROM skaffolder/java-oracle-base
