/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e2456320cfc6233ae9336d8
*
* You will get 10% discount for each one of your friends
* 
*/

import { Observable } from 'rxjs/Rx';
import { Http, RequestOptions, Headers, Response } from '@angular/http';
import { Injectable } from '@angular/core';
import { config } from "../../../config/properties";
import { User } from '../../domain/manage_film_example_db/user';
import 'rxjs/add/operator/map';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR MANAGE SECURITY
 */
@Injectable()
export class SecurityService {

    contextUrl:string = config.host;
    constructor(private http: Http) { }
    
    /**
     * Verify JWT token
     */
    verifyToken(token:string): Observable<User> {
        return this.http.post(this.contextUrl + "/verifyToken", {token: token})
        .map(response => response.json() as User);
    }

    /**
     * Login by username and SHA-3 password
     */
    login(username: string, password:string): Observable<User> {
        return this.http
            .post(this.contextUrl + "/login", { username: username, password: password } )
            .map(response => response.json() as User);
    }
    
    /**
     * Change password for logged user
     */
    changePassword(passwordNew:string, passwordOld:string): Observable<void> {
        return this.http
            .post(this.contextUrl + '/changePassword' , {
                passwordNew: passwordNew, 
                passwordOld: passwordOld 
            })
            .map(response => response.json())
    }
    
}