/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e2456320cfc6233ae9336d8
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { ActivatedRoute, Params } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';

// Import Services
import { ActorService } from '../../services/actor.service';
import { FilmService } from '../../services/film.service';

// Import Models
import { Actor } from '../../domain/manage_film_example_db/actor';

import { Film } from '../../domain/manage_film_example_db/film';

// START - USED SERVICES
/*
 *	ActorService.create
 *		PARAMS: 
 *		
 *
 *	FilmService.findBycast
 *		PARAMS: 
 *					Objectid key - Id della risorsa cast da cercare
 *		
 *
 *	ActorService.get
 *		PARAMS: 
 *					ObjectId id - Id resource
 *		
 *
 *	ActorService.update
 *		PARAMS: 
 *					ObjectId id - Id
 *		
 *
 */
// END - USED SERVICES

// START - REQUIRED RESOURCES
/*
 * ActorService  
 * FilmService  
 */
// END - REQUIRED RESOURCES

/**
 * Edit component for ActorEdit
 */
@Component({
    selector: 'actor-edit',
    templateUrl : './actor-edit.component.html',
    styleUrls: ['./actor-edit.component.css']
})
export class ActorEditComponent implements OnInit {

    item: Actor;
    listCast: Actor[];
	externalFilm: Film[];
    model: Actor;
    
    constructor(
        private actorService: ActorService,
        private filmService: FilmService,
        private route: ActivatedRoute,
        private location: Location) {
        // Init item
        this.item = new Actor();
	   this.externalFilm = [];
    }

    ngOnInit(): void {
            this.route.params.subscribe(param => {
                let id: string = param['id'];
                if (id !== 'new') {
                    // Get item from server 
                    this.actorService.get(id).subscribe(item => this.item = item);
                    
                    
                    this.filmService.findByCast(id).subscribe(list => this.externalFilm = list);
                    
                }
            });
    }

    /**
     * Save Item
     */
    save (formValid:boolean, item: Actor): void{
        if (formValid) {
            if(item._id){
                this.actorService.update(item).subscribe(data => this.goBack());
            } else {
                this.actorService.create(item).subscribe(data => this.goBack());
            }  
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }
    

}