/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e2456320cfc6233ae9336d8
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { ActivatedRoute, Params } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';

// Import Services
import { FilmMakerService } from '../../services/film-maker.service';
import { FilmService } from '../../services/film.service';

// Import Models
import { FilmMaker } from '../../domain/manage_film_example_db/film-maker';

import { Film } from '../../domain/manage_film_example_db/film';

// START - USED SERVICES
/*
 *	FilmMakerService.create
 *		PARAMS: 
 *		
 *
 *	FilmService.findByfilmMaker
 *		PARAMS: 
 *					Objectid key - Id della risorsa filmMaker da cercare
 *		
 *
 *	FilmMakerService.get
 *		PARAMS: 
 *					ObjectId id - Id resource
 *		
 *
 *	FilmMakerService.update
 *		PARAMS: 
 *					ObjectId id - Id
 *		
 *
 */
// END - USED SERVICES

// START - REQUIRED RESOURCES
/*
 * FilmService  
 * FilmMakerService  
 */
// END - REQUIRED RESOURCES

/**
 * Edit component for FilmMakerEdit
 */
@Component({
    selector: 'film-maker-edit',
    templateUrl : './film-maker-edit.component.html',
    styleUrls: ['./film-maker-edit.component.css']
})
export class FilmMakerEditComponent implements OnInit {

    item: FilmMaker;
    listFilmMaker: FilmMaker[];
	externalFilm: Film[];
    model: FilmMaker;
    
    constructor(
        private filmmakerService: FilmMakerService,
        private filmService: FilmService,
        private route: ActivatedRoute,
        private location: Location) {
        // Init item
        this.item = new FilmMaker();
	   this.externalFilm = [];
    }

    ngOnInit(): void {
            this.route.params.subscribe(param => {
                let id: string = param['id'];
                if (id !== 'new') {
                    // Get item from server 
                    this.filmmakerService.get(id).subscribe(item => this.item = item);
                    
                    
                    this.filmService.findByFilmMaker(id).subscribe(list => this.externalFilm = list);
                    
                }
            });
    }

    /**
     * Save Item
     */
    save (formValid:boolean, item: FilmMaker): void{
        if (formValid) {
            if(item._id){
                this.filmmakerService.update(item).subscribe(data => this.goBack());
            } else {
                this.filmmakerService.create(item).subscribe(data => this.goBack());
            }  
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }
    

}