/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e2456320cfc6233ae9336d8
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { ActivatedRoute, Params } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';

// Import Services
import { ElectrobergsolutionsService } from '../../services/electrobergsolutions.service';

// Import Models
import { Electrobergsolutions } from '../../domain/manage_film_example_db/electrobergsolutions';

// START - USED SERVICES
/*
 *	electrobergsolutionsService.create
 *		PARAMS: 
 *					electrobergsolutions obj - Object to insert
 *		
 *
 *	electrobergsolutionsService.get
 *		PARAMS: 
 *					ObjectId id - Id electrobergsolutions
 *		RETURN: electrobergsolutions
 *				
 *
 *	electrobergsolutionsService.update
 *		PARAMS: 
 *					ObjectId id - Id electrobergsolutions
 *		RETURN: electrobergsolutions
 *				
 *
 */
// END - USED SERVICES

// START - REQUIRED RESOURCES
/*
 * electrobergsolutionsService  
 */
// END - REQUIRED RESOURCES

/**
 * Edit component for electrobergsolutionsEdit
 */
@Component({
    selector: 'electrobergsolutions-edit',
    templateUrl : './electrobergsolutions-edit.component.html',
    styleUrls: ['./electrobergsolutions-edit.component.css']
})
export class ElectrobergsolutionsEditComponent implements OnInit {

    item: Electrobergsolutions;
    model: Electrobergsolutions;
    
    constructor(
        private electrobergsolutionsService: ElectrobergsolutionsService,
        private route: ActivatedRoute,
        private location: Location) {
        // Init item
        this.item = new Electrobergsolutions();
    }

    ngOnInit(): void {
            this.route.params.subscribe(param => {
                let id: string = param['id'];
                if (id !== 'new') {
                    // Get item from server 
                    this.electrobergsolutionsService.get(id).subscribe(item => this.item = item);
                    
                    
                }
            });
    }

    /**
     * Save Item
     */
    save (formValid:boolean, item: Electrobergsolutions): void{
        if (formValid) {
            if(item._id){
                this.electrobergsolutionsService.update(item).subscribe(data => this.goBack());
            } else {
                this.electrobergsolutionsService.create(item).subscribe(data => this.goBack());
            }  
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }
    

}